### ISSUE TITLE
Doesn't Work...

### ISSUE THREAD

**Issue by Desmo5574** [MrSanZz/InsomniaGPT-Prompt#7]
Have an OpenAI key, attempted quite a few times to input and the following error always happens:

Error: Please contact : https://t.me/MrSanZzXe 

E :  {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

InsomniaGPT:  None
Traceback (most recent call last):
  File "/vol1/Source/InsomniaGPT-Prompt/insomniagpt.py", line 243, in <module>
    saving.bot(ai_response)
  File "/vol1/Source/InsomniaGPT-Prompt/insomniagpt.py", line 136, in bot
    log(target)
  File "/vol1/Source/InsomniaGPT-Prompt/insomniagpt.py", line 132, in log
    file.write(str('InsomniaGPT: '+answer))
                   ~~~~~~~~~~~~~~~^~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by MrSanZz** [comment]
You need to pay the api key bills :) !

or you can use this method:

1. create a new gmail account
2. then create a new openai account
3. generate the api key
4. enjoy your api key

**Comment by allatfortheone** [comment]
did that and I'm still getting an error
